name: Build CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps
        run: pnpm install

      - name: build
        run: pnpm run build

      # - name: Copy the Files
      #   run: |
      #     cp -r "./apps/docs/dist" "./docs"

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b gh-pages
          git add .
          git commit -a -m "Add Docs Changes"
          git push -f -u origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
